# Monochrome terminal prompt

add_newline = false

format = """
$directory
$character"""

right_format = ""

continuation_prompt = "> "

[directory]
home_symbol = "~"
truncation_length = 3
truncate_to_repo = false
style = "white"
format = "[$path]($style)"

[character]
success_symbol = "> "
error_symbol = "> "

[username]
disabled = true

[hostname]
disabled = true

[cmd_duration]
disabled = true

[time]
disabled = true

[jobs]
disabled = true

[localip]
disabled = true

[sudo]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[git_metrics]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true
